myapp/urls.py
from myapp import views
from django.urls import path,re_path

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('administrator_login/', views.administrator_login, name='administrator_login'),
    path('manager_login/', views.manager_login, name='manager_login'),
    path('administrator_home/', views.administrator_home, name='administrator_home'),
    path('manager_home/', views.manager_home, name='manager_home'),
    path('profile_information/', views.profile_information, name='profile_information'),
    path('warehouse/', views.warehouse, name='warehouse'),
    path('record/', views.record, name='record'),
    path('add_admin/', views.add_admin, name='add_admin'),
    path('edit_admin/', views.edit_admin, name='edit_admin'),
    path('delete_admin/', views.delete_admin, name='delete_admin'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('check_product/', views.check_product, name='check_product'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/', views.edit_product, name='edit_product')
]

warehouse_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from myapp import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('myapp/', include('myapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
# from login.models import Manager

class Administrator(models.Model):
    admin_id = models.IntegerField(primary_key=True)
    manager_name = models.ForeignKey('Manager', models.DO_NOTHING, db_column='manager_name')
    admin_name = models.CharField(max_length=255, blank=True, null=True)
    admin_pw = models.CharField(max_length=255)
    admin_age = models.IntegerField(blank=True, null=True)
    admin_email = models.CharField(max_length=255, blank=True, null=True)
    admin_telephone = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'administrator'

class Manager(models.Model):
    manager_name = models.CharField(primary_key=True, max_length=255)
    manager_pw = models.CharField(max_length=255)
    manager_age = models.IntegerField(blank=True, null=True)
    manager_email = models.CharField(max_length=255, blank=True, null=True)
    manager_telephone = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'manager'


class Product(models.Model):
    product_id = models.IntegerField(primary_key=True)
    warehouse = models.ForeignKey('Warehouse', models.DO_NOTHING)
    name = models.CharField(max_length=255, blank=True, null=True)
    type = models.CharField(max_length=255, blank=True, null=True)
    purchase_price = models.FloatField(blank=True, null=True)
    selling_price = models.FloatField(blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)
    supplier = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'product'


class Record(models.Model):
    record_id = models.IntegerField(primary_key=True)
    product = models.ForeignKey(Product, models.DO_NOTHING)
    warehouse_id = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'record'


class Warehouse(models.Model):
    warehouse_id = models.IntegerField(primary_key=True)
    admin = models.ForeignKey(Administrator, models.DO_NOTHING)
    address = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'warehouse'

class AdminProfile(models.Model):
    admin = models.OneToOneField(Administrator, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', default='default.jpg', blank=True)

    def __str__(self):
        return self.admin.admin_name

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from myapp import models
import pymysql
import tkinter.messagebox
from tkinter import *

# 网站默认界面
def index(request):
    context_dict = {}
    context_dict['boldmessage'] = '网站默认界面，显示酒厂的信息和两种登陆方法的链接！'
    return render(request, 'myapp/index.html', context=context_dict)

# 经理登录
def manager_login(request):
    if request.method == 'POST':
        manager_name = request.POST.get('manager_name')
        manager_password = request.POST.get('manager_password')
        if manager_name and manager_password:
            name = manager_name.strip()
            try:
                manager = models.Manager.objects.get(manager_name=name)
            except:
                return render(request, 'myapp/index.html')
            if manager.manager_pw == manager_password:
                return redirect('myapp:manager_home')

    return render(request, 'myapp/manager_login.html')

# admin登录
def administrator_login(request):
    if request.method == 'POST':
        administrator_name = request.POST.get('administrator_name')
        administrator_password = request.POST.get('administrator_password')
        if administrator_name and administrator_password:
            name = administrator_name.strip()
            try:
                administrator = models.Administrator.objects.get(admin_name=name)
            except:
                return render(request, 'myapp/index.html')
            if administrator.admin_pw == administrator_password:
                request.session['admin_id'] = administrator.admin_id
                return render(request, 'myapp/administrator_home.html')

    return render(request, 'myapp/administrator_login.html')

# 经理主界面，直接显示所用admin的信息
def manager_home(request):
    context_dict = {}
    conn = pymysql.connect(host='localhost', user='root', password='12345678', db='drinks', charset='utf8')
    with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
        cursor.execute('SELECT admin_id,admin_name,admin_pw,admin_age,admin_email,admin_telephone FROM administrator')
        administrators = cursor.fetchall()
    context_dict['administrators'] = administrators
    return render(request, 'myapp/manager_home.html', context_dict)

# 添加admin账户
def add_admin(request):
    if request.method == 'GET':
        return render(request, 'myapp/add_admin.html')
    else:
        admin_name = request.POST.get('admin_name', '')
        admin_pw = request.POST.get('admin_pw', '')
        manager_name = request.POST.get('manager_name')
        conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
        with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
            cursor.execute("INSERT INTO administrator (admin_name,admin_pw,manager_name)"
                           "values (%s,%s,%s)", [admin_name,admin_pw,manager_name])
            conn.commit()
    return render(request, 'myapp/manager_login.html')

# 修改admin账户
def edit_admin(request):
    if request.method == 'GET':
        admin_id = request.GET.get('admin_id')
        context_dict = {}
        conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
        with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
            cursor.execute("SELECT admin_id,admin_name,admin_pw FROM administrator where admin_id =%s", [admin_id])
            admin = cursor.fetchone()
        context_dict['administrator'] = admin
        return render(request, 'myapp/edit_admin.html', context_dict)
    else:
        admin_id = request.POST.get('admin_id')
        admin_name = request.POST.get("admin_name")
        admin_pw = request.POST.get('admin_pw', '')
        conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
        with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
            cursor.execute("UPDATE administrator SET admin_name=%s,admin_pw=%s where admin_id =%s",
                           [admin_name, admin_pw, admin_id])
            conn.commit()
        return render(request, 'myapp/manager_login.html')

def delete_admin(request):
    admin_id = request.GET.get('admin_id')
    conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
    with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
        cursor.execute("DELETE FROM administrator WHERE admin_id=%s",[admin_id])
        conn.commit()
    return render(request, 'myapp/manager_login.html')

# admin主界面
def administrator_home(request):
    return render(request, 'myapp/administrator_home.html')

def profile_information(request):
    admin_id = request.session.get('admin_id')
    context_dict = {}
    conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
    with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
        cursor.execute("SELECT admin_id,admin_name,admin_pw,admin_age,admin_email,admin_telephone FROM administrator where admin_id =%s", [admin_id])
        admin = cursor.fetchone()
    context_dict['administrator'] = admin
    return render(request, 'myapp/profile_information.html', context_dict)

def edit_profile(request):
    if request.method == 'GET':
        admin_id = request.GET.get('admin_id')
        context_dict = {}
        conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
        with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
            cursor.execute("SELECT admin_id,admin_name,admin_pw,admin_age, admin_email, admin_telephone FROM administrator where admin_id =%s", [admin_id])
            admin = cursor.fetchone()
        context_dict['administrator'] = admin
        return render(request, 'myapp/edit_profile.html', context_dict)
    else:
        admin_id = request.POST.get('admin_id')
        admin_name = request.POST.get("admin_name")
        admin_pw = request.POST.get('admin_pw', '')
        admin_age = request.POST.get('admin_age')
        admin_email = request.POST.get('admin_email')
        admin_telephone = request.POST.get('admin_telephone')
        conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
        with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
            cursor.execute("UPDATE administrator SET admin_name=%s,admin_pw=%s,admin_age=%s,admin_email=%s,admin_telephone=%s where admin_id =%s",
                           [admin_name, admin_pw, admin_age, admin_email, admin_telephone, admin_id])
            conn.commit()
        return render(request, 'myapp/administrator_login.html')

def warehouse(request):
    admin_id = request.session.get('admin_id')
    warehouse = models.Warehouse.objects.get(admin_id=admin_id)
    warehouse_id = warehouse.warehouse_id
    context_dict = {}
    conn = pymysql.connect(host='localhost', user='root', password='12345678', db='drinks', charset='utf8')
    with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
        cursor.execute('SELECT product_id,name,type,number FROM product WHERE warehouse_id=%s',
                       [warehouse_id])
        products = cursor.fetchall()
    context_dict['products'] = products
    context_dict['warehouse_id'] = warehouse_id
    return render(request, 'myapp/warehouse.html', context_dict)

def check_product(request):
    product_id = request.GET.get('product_id')
    context_dict = {}
    conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
    with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
        cursor.execute(
            'SELECT product_id,name,type,purchase_price,selling_price,number,supplier FROM product WHERE product_id=%s',
                       [product_id]
        )
        product = cursor.fetchone()
    context_dict['product'] = product
    return render(request, 'myapp/check_product.html',context_dict)

def add_product(request):
    if request.method == 'GET':
        return render(request, 'myapp/add_product.html')
    else:
        warehouse_id = request.POST.get('warehouse_id', '')
        name = request.POST.get('name','')
        type = request.POST.get('type','')
        purchase_price = request.POST.get('purchase_price', '')
        selling_price = request.POST.get('selling_price', '')
        number = request.POST.get('number', '')
        supplier = request.POST.get('supplier', '')
        conn = pymysql.connect(host="localhost", user="root", passwd="12345678", db="drinks", charset='utf8')
        with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
            cursor.execute(
                "INSERT INTO product (warehouse_id,name,type,purchase_price,selling_price,number,supplier)"
                           "values (%s,%s,%s,%s,%s,%s,%s)", [warehouse_id,name,type,purchase_price,selling_price,number,supplier])
            conn.commit()
        product_new = models.Product.objects.get(name = name, type = type, warehouse_id=warehouse_id, number = number)
        product_id = product_new.product_id
        with conn.cursor(cursor=pymysql.cursors.DictCursor) as cursor:
            cursor.execute(
                "INSERT INTO record (product_id,warehouse_id,number) values (%s,%s,%s)",
                [product_id,warehouse_id,number])
            conn.commit()
    return render(request, 'myapp/administrator_login.html')

def edit_product(request):
        if request.method == 'GET':
            product_id = request.GET.get('product_id')
            global number_old
            global warehouse_id_temp
            product = models.Product.objects.get(product_id = product_id)
            number_old = int(product.number)
            warehouse_id_temp = product.warehouse_id
            context_dict = {}

templates/myapp/add_admin.html
{% extends 'myapp/base_manager.html' %}
{% load staticfiles %}

{% block title_block %}
	Add Administrators
{% endblock %}

{% block body_block %}
    <form method="post" action="{% url 'myapp:add_admin' %}">
        {% csrf_token %}
        <table>
            <tr>
                <th>Name</th>
                <td>
                    <input name="admin_name">
                </td>
            </tr>
            <tr>
                <th>Password</th>
                <td>
                    <input name="admin_pw" />
                </td>
            </tr>
            <tr>
                <th>Manager Name</th>
                <td>
                    <input name="manager_name" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" value="submit"/>
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

templates/myapp/administrator_home.html
{% extends 'myapp/base_administrator.html' %}
{% load staticfiles %}

{% block title_block %}
	Administrator Home
{% endblock %}

{% block body_block %}
	<h1>Welcome back!</h1>

<!--	<div>-->
<!--		<ul>-->
<!--			<li><a href="{% url 'myapp:profile_information' %}">Profile</a></li>-->
<!--			<li><a href="{% url 'myapp:warehouse' %}">Warehouse Status</a></li>-->
<!--			<li><a href="{% url 'myapp:record' %}">Record List</a></li>-->
<!--		</ul>-->
<!--	</div>-->
{% endblock %}

templates/myapp/administrator_login.html
{% extends 'myapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Administrator Login
{% endblock %}

{% block body_block %}
	<h1>Administrator Login Page</h1>

    <form id="administrator_form" method="post" action="{% url 'myapp:administrator_login' %}">
		{% csrf_token %}
		Administrator Name: <input type="text" name="administrator_name" value="" size="50" />
		<br />
		Password: <input type="password" name="administrator_password" value="" size="50" />
		<br />
		<input type="submit" value="submit" />
	</form>


{% endblock %}

templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Warehouse Management System -
            {% block title_block %}
                Default content.
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
    </body>
</html>

templates/myapp/base_administrator.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Warehouse Management System -
            {% block title_block %}
                Default content.
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <!--sidebar-->
        <div>
            <ul>
                <li><a href="{% url 'myapp:personal_information' %}">Personal Information</a></li>
                <li><a href="{% url 'myapp:warehouse' %}">Warehouse Status</a></li>
                <li><a href="{% url 'myapp:record' %}">Record List</a></li>
            </ul>
        </div>
        <div>
          <a href="{% url 'myapp:index' %}">Log out</a>
        </div>
    </body>
</html>

templates/myapp/base_manager.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Warehouse Management System -
            {% block title_block %}
                Default content.
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div>
          <a href="{% url 'myapp:index' %}">Log out</a>
        </div>
    </body>
</html>

templates/myapp/check_product.html
{% extends 'myapp/base_administrator.html' %}
{% load staticfiles %}

{% block title_block %}
	Check product
{% endblock %}

{% block body_block %}

	<table class="table">
		<p>这里应该放product的图片！</p>

		<tr>
			<th>Product_id</th>
			<th>Name</th>
			<th>Type</th>
			<th>Purchase_price</th>
			<th>Selling_price</th>
			<th>Number</th>
			<th>Supplier</th>
		</tr>
		<tr>
            <td align="center"> {{ product.product_id }} </td>
			<td align="center"> {{ product.name }} </td>
			<td align="center"> {{ product.type }} </td>
			<td align="center"> {{ product.purchase_price }} </td>
			<td align="center"> {{ product.selling_price }} </td>
			<td align="center"> {{ product.number }} </td>
			<td align="center"> {{ product.supplier }} </td>
			<td align="center">
				<!--这个是modify按钮-->
				<a href="../edit_product/?product_id={{ product.product_id }}">modify</a>
			</td>
		</tr>
	</table>
{% endblock %}

templates/myapp/edit_product.html
{% extends 'myapp/base_administrator.html' %}
{% load staticfiles %}

{% block title_block %}
	Edit Products
{% endblock %}

{% block body_block %}

	<form method="post" action="{% url 'myapp:edit_product' %}">
        {% csrf_token %}
        <input type="hidden" name="product_id" value="{{ product.product_id }}" />
        <table>
            <tr>
                <th>Name:</th>
                <td>
                    <input name="name" />
                </td>
            </tr>
            <tr>
                <th>Type:</th>
                <td>
                    <input name="type" />
                </td>
            </tr>
			<tr>
                <th>Purchase_price:</th>
                <td>
                    <input name="purchase_price" />
                </td>
            </tr>
			<tr>
                <th>Selling_price:</th>
                <td>
                    <input name="selling_price" />
                </td>
            </tr>
			<tr>
                <th>Number:</th>
                <td>
                    <input name="number" />
                </td>
            </tr>
            <tr>
                <th>Supplier:</th>
                <td>
                    <input name="supplier" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" value="submit"/>
                </td>
            </tr>
        </table>
    </form>

{% endblock %}

templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Welcome Page
{% endblock %}

{% block body_block %}
	<h1>Welcome to Warehouse Management System!</h1>
		<div>
			<strong>{{ boldmessage }}</strong><br />
		</div>

		<div>
			<a href="{% url 'myapp:manager_login' %}">Manager Login</a> <br />
			<a href="{% url 'myapp:administrator_login' %}">Administrator Login</a>
		</div>

{% endblock %}

<!--<!DOCTYPE html>-->

<!--{% load staticfiles %} &lt;!&ndash; New line &ndash;&gt;-->

<!--<html>-->
<!--	<head>-->
<!--		<title>Rango</title>-->
<!--	</head>-->

<!--	<body>-->
<!--		<h1>Rango says ... </h1>-->
<!--		<div>-->
<!--			hey there partner! <br />-->
<!--			<strong>{{ boldmessage }}</strong><br />-->
<!--		</div>-->

<!--		<div>-->
<!--			<h2>Most Liked Categories</h2>-->
<!--			{% if categories %}-->
<!--			<ul>-->
<!--				{% for category in categories %}-->
<!--				<li>-->
<!--					<a href="{% url 'rango:show_category' category.slug %}"> {{ category.name }}</a>&lt;!&ndash;changed in 8.1&ndash;&gt;-->
<!--				</li>-->
<!--				{% endfor %}-->
<!--			</ul>-->
<!--			{% else %}-->
<!--			<strong>There are no categories present.</strong>-->
<!--			{% endif %}-->
<!--		</div>-->

<!--		<div>-->
<!--			<h2>Most Viewed Pages</h2>-->
<!--			{% if pages %}-->
<!--			<ul>-->
<!--				{% for page in pages %}-->
<!--				<li>-->
<!--					<a href="{{ page.url }}">{{ page.title }}</a>-->
<!--				</li>-->
<!--				{% endfor %}-->
<!--			</ul>-->
<!--			{% else %}-->
<!--			<strong>There are no pages present.</strong>-->
<!--			{% endif %}-->
<!--		</div>-->

<!--		<div>-->
<!--			<a href="{% url 'rango:about' %}">A link to the about page.</a><br />&lt;!&ndash;changed in 8.1&ndash;&gt;-->
<!--			<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />-->
<!--		</div>-->

<!--		<div>-->
<!--			<a href="/rango/add_category/">Add a New Category.</a><br />-->
<!--		</div>-->
<!--	</body>-->
<!--</html>-->

templates/myapp/manager_home.html
{% extends 'myapp/base_manager.html' %}
{% load staticfiles %}

{% block title_block %}
	Administrator Information Page
{% endblock %}

{% block body_block %}

	<table class="table">
		<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Password</th>
		<th>Email</th>
		<th>Telephone</th>
	</tr>
	{% for admin in administrators %}
		<tr>
            <td align="center"> {{ admin.admin_name }} </td>
			<td align="center"> {{ admin.admin_age }} </td>
			<td align="center"> {{ admin.admin_pw }} </td>
			<td align="center"> {{ admin.admin_email }} </td>
			<td align="center"> {{ admin.admin_telephone }} </td>
			<td align="center">
				<!--这两个就是编辑和删除按钮-->
				<a href="../edit_admin/?admin_id={{ admin.admin_id }}">edit</a>
				<a href="../delete_admin/?admin_id={{ admin.admin_id }}">delete</a>
			</td>
		</tr>
	{% endfor %}
	</table>

	<a href="{% url 'myapp:add_admin'%}">Add administrators</a>
{% endblock %}

templates/myapp/manager_login.html
{% extends 'myapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Manager Login
{% endblock %}

{% block body_block %}
	<h1>Manager Login Page</h1>

	<form id="manager_form" method="post" action="{% url 'myapp:manager_login' %}">
	{% csrf_token %}
	Manager Name: <input type="text" name="manager_name" value="" size="50" />
	<br />
	Password: <input type="password" name="manager_password" value="" size="50" />
	<br />
	<input type="submit" value="submit" />
	</form>

{% endblock %}

templates/myapp/profile_information.html
{% extends 'myapp/base_administrator.html' %}
{% load staticfiles %}

{% block title_block %}
	Profile Information
{% endblock %}

{% block body_block %}

	<h1>{{ administrator.admin_name }}</h1>

	<div>
		<p>这里应该显示admin的头像！<p/>
		<p>Admin Age: {{ administrator.admin_age }}</p>
		<p>Admin Email: {{ administrator.admin_email }}</p>
		<p>Admin Telephone: {{ administrator.admin_telephone }}</p>
	</div>

	<a href="../edit_profile/?admin_id={{ administrator.admin_id }}">edit</a>

{% endblock %}

templates/myapp/record.html
{% extends 'myapp/base_administrator.html' %}
{% load staticfiles %}

{% block title_block %}
	Record List
{% endblock %}

{% block body_block %}
	<h1>Records for Warehouse {{ warehouse_id }}</h1>

	<table class="table">
		<tr>
			<th>Product_id</th>
			<th>Warehouse_id</th>
			<th>Number of changes</th>
		</tr>
		{% for record in records %}
		<tr>
			<td align="center"> {{ record.product_id }} </td>
			<td align="center"> {{ record.warehouse_id }} </td>
			<td align="center"> {{ record.number }} </td>
		</tr>
		{% endfor %}
	</table>

{% endblock %}

templates/myapp/warehouse.html
{% extends 'myapp/base_administrator.html' %}
{% load staticfiles %}

{% block title_block %}
	Warehouse Status
{% endblock %}

{% block body_block %}
	<h1>Warehouse ID: {{ warehouse_id }}</h1>

	<table class="table">
		<tr>
			<th>Product_id</th>
			<th>Name</th>
			<th>Type</th>
			<th>Number</th>
		</tr>
		{% for product in products %}
		<tr>
            <td align="center"> {{ product.product_id }} </td>
			<td align="center"> {{ product.name }} </td>
			<td align="center"> {{ product.type }} </td>
			<td align="center"> {{ product.number }} </td>
			<td align="center">
				<!--这个就是查看按钮-->
				<a href="../check_product/?product_id={{ product.product_id }}">check</a>
			</td>
		</tr>
		{% endfor %}
	</table>

	<a href="{% url 'myapp:add_product' %}">Add products</a>
{% endblock %}